config.tomlファイルの設定方法を記載した資料を追加。
Jij-Inc/JijHandsOnMaterials pull request #8
Opened 2022-10-03 08:41 UTC by K-Suzuki-Jij

config.tomlファイルの設定方法を記載した資料を追加しました。

2022-10-03 23:19 UTC, j-i-k-o requested changes
`.DS_Store`を削除 + `.gitignore`に追加していただけるとありがたいです。

2022-10-03 23:38 UTC, j-i-k-o commented
それ以外は問題無いと思います！

2022-10-04 02:16 UTC, K-Suzuki-Jij commented
ありがとうございます。削除して.gitignoreに追加しました。

2022-10-06 03:39 UTC, j-i-k-o approved these changes
マージいただけるとありがたいです！

2022-10-06 04:14 UTC, merged